### PR TITLE
Added direction to enter and leave event

### PR DESCRIPTION
**Pull request by liqueflies**
Added parameter `direction` to `'enter'` and `'leave'` callback.
added sinon for testing, and test for direction parameter.

### CODE REVIEW

**Comment by silvestreh** [comment]
Hey! Thanks for the Pull Request. The build is failing on Travis CI. Apparently due to some linting issues:

```shell
/home/travis/build/silvestreh/onScreen/test/index_test.js
    error  'calledCallback' is defined but never used                 no-unused-vars
    error  'calledCallback' is never reassigned, use 'const' instead  prefer-const
    error  Block must not be padded by blank lines                    padded-blocks
```

**Comment by silvestreh** [comment]
Some other things I'm noticing… Would you care to explain these?

* Why would [`scrollTop`](https://github.com/silvestreh/onScreen/pull/36/files#diff-6d186b954a58d5bb740f73d84fe39073R21) be public?
* Could the [`direction`](https://github.com/silvestreh/onScreen/pull/36/files#diff-0d846e4afc73520eebcc1a44c6484810R20) parameter be part of the options object?
* What's the benefit of knowing the direction? I'm thinking that you could check which direction you're scrolling outside the library while implementing it in a project… something like:

```javascript
const os = new OnScreen();
const direction = {
    up() { /* implement to return true */ },
    down() { /* implement to return true */ },
    left() { /* implement to return true */ },
    right() { /* implement to return true */ },
};

os.on('enter', (element) => {
    if (direction.up) {
        // do something
    }
});
```

* Finally: if I end up merging this PR we'll need documentation for it 😄 

Thanks!

**Comment by Liqueflies** [comment]
> the feature seems to only cover vertical scrolling

you're right, i'll fix soon

> Why would scrollTop be public?

I just put it as object prop, the idea is to set a default value then on scroll (the function debouncedScroll) check the direction

> Could the direction parameter be part of the options object?

not sure to understand. you want object direction on options and then set when is on debounceScroll?

> What's the benefit of knowing the direction? I'm thinking that you could check which direction you're scrolling outside the library while implementing it in a project

yes, I was able to extends OnScreen also and hack this feature, but why bind another scroll event? With onscreen you can get also direction and decide to use it or not :) For that reason I decided to try improve with this feature.

I will update you with fixes if you want, thanks a lot!

**Comment by Liqueflies** [comment]
Added `direction` object, now you can check with 

`if(direction.up) { /* tell me baby */ }`

test updated.

docs updated ! 👍 

build passed on travis it seems !  🎉 

if you don't like something feel free to change, or to tell me what you prefer.

Thank you for feedback! :)

**Comment by caiter78** [comment]
Hi, for internet explorer fix direction I used
	x: window.pageXOffset || document.documentElement.scrollLeft,
        y: window.pageYOffset || document.documentElement.scrollTop

**Comment by liqueflies** [comment]
Added also pageXOffset and pageYOffset for solving compatibility issue.
Thanks @caiter78

**Pull request closed without merging**
